- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: copy expense conf into nginx
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: import commmon role from commmon folder
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: copy filebeat yml
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml