- name: copy filebeat repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install filebeat
  ansible.builtin.dnf:
    name: filebeat
    state: installed

- name: start filebeat
  ansible.builtin.systemd:
    name: filebeat
    enabled: yes
    state: restarted
    daemon-reload: yes