- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: copy elasticsearch repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/filebeat.repo
- name: install elasticsearch
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed
- name: copy elasticsearch yaml
  ansible.builtin.template:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
- name: copy nginx conf
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: restarted
    daemon-reload: yes
- name: restart elasticsearch service
  ansible.builtin.systemd:
    name: elasticsearch
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: install kibana
  ansible.builtin.dnf:
    name: kibana
    state: installed
- name: copy kibana yml conf
  ansible.builtin.template:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
- name: start kibana
  ansible.builtin.systemd:
    name: kibana
    enabled: yes
    state: restarted
    daemon-reload: yes

- name: install logstash
  ansible.builtin.dnf:
    name: logstash
    state: installed
- name: copy logstash conf
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
- name: start logstash
  ansible.builtin.systemd:
    name: logstash
    enabled: yes
    state: restarted
    daemon-reload: yes