- name: create a directory
  ansible.builtin.file:
    path: /node
    state: directory

- name: install node exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
    dest: /node
    remote_src: yes

- name: copy  node exporter service
  ansible.builtin.template:
    src: node-exporter.service
    dest: /etc/systemd/system/node-exporter.service

- name: start node exporter service
  ansible.builtin.systemd:
    name: node-exporter
    enabled: yes
    state: restarted
    daemon-reload: yes