route:
  group_by: ['alertname']
  group_wait: 1m
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'email'

receivers:
  - name: "email"
    email_configs:
      - to: "a24121068@gmail.com"
        from: "a24121068@gmail.com"
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
        auth_username: "{{ lookup('aws_ssm', 'alertmanager_username', region='us-east-1') }}"
        auth_password: "{{ lookup('aws_ssm', 'alertmanager_password', region='us-east-1') }}"
        require_tls: true
