route:
  group_by: ['alertname']
  group_wait: 1m
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'email'

receivers:
  - name: "email"
    email_configs:
      - to: "a24121068@gmail.com"
        from: "a24121068@gmail.com"
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
        auth_username: "AKIA47CRXJA24P2BPI7N"
        auth_password: "BL3Q8YipKyV9Wnde1sKQ/h3hx46Ockq4Ooje3lB9wfjR"
        require_tls: true
