groups:
- name: server down alert
  rules:
  - alert: server_down_alert
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Server down alert

  - alert: frontend_service_down_alert
    expr: node_systemd_unit_state{exported_name="nginx.service",state="active"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Frontend Service down alert

  - alert: backend_service_down_alert
    expr: node_systemd_unit_state{exported_name="backend.service",state="active"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Backend Service down alert

  - alert: mysqld_service_down_alert
    expr: node_systemd_unit_state{exported_name="mysqld.service",state="active"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: mysql Service down alert