groups:
- name: server down alert
  rules:
  - alert: server_down_alert
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Server down alert

  - alert: frontend_service_down_alert
    expr: node_systemd_unit_state{job="expense", state="active", exported_name="nginx.service"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Frontend Service down alert

  - alert: backend_service_down_alert
    expr: node_systemd_unit_state{job="expense", state="active", exported_name="backend.service"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Backend Service down alert

  - alert: mysqld_service_down_alert
    expr: node_systemd_unit_state{job="expense", state="active", exported_name="mysqld.service"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: mysql Service down alert

  - alert: High cpu usage alert
    expr: (100 - avg by (name) (rate(node_cpu_seconds_total{mode="idle"}[1m])*100)) > 80
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: high cpu usage alert

  - alert: High cpu usage alert
    expr: node_free_percentage > 80
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: high memory usage alert