groups:
  - name: node_free_percentage
    rules:
    - record: node_free_percentage
      expr: 100 - (((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes) * 100)